'use strict';

module.exports = {
	ARRAY: "ARRAY",
	CARET: "CARET",
	COMMAND: "COMMAND",
	FUNCTION_CALL: "FUNCTION_CALL",
	LITERAL: "LITERAL",
	LOOP: "LOOP",
	NORMAL: "NORMAL",
	PROGRAM: "PROGRAM",
	SUBSHELL: "SUBSHELL"
}
